### ISSUE TITLE
awwwwwwwwwwww

### ISSUE THREAD

**Issue by Smart6502** [segfaultdev/awlang#1]
awwwwwwwwwwwwwwlang is nice

**Comment by argvsc47** [comment]
awwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by segfaultdev** [comment]
I understand, this seems like a really serious and important issue that we will take into account in the future, thank you a lot.

**Comment by argvsc47** [comment]
awwwwwww thank you for taking this issue into consideration it makes me go awwwwwwwwwwwwwwwww

**Comment by Smart6502** [comment]
> I understand, this seems like a really serious and important issue that we will take into account in the future, thank you a lot.

awwwwwww very serious awwwwwwwwwwwww

**Comment by argvsc47** [comment]
> > I understand, this seems like a really serious and important issue that we will take into account in the future, thank you a lot.
> 
> awwwwwww very serious awwwwwwwwwwwww

awwww

**Comment by Smart6502** [comment]
yes very awwwww

**Comment by Smart6502** [comment]
make this the motto of awlang
